### ISSUE TITLE
Alterar test_kits ZIKA_PCR para ZIKV_PCR em Target

### ISSUE THREAD

**Issue by mathdesilva** [InstitutoTodosPelaSaude/arbo#154]
Fazer a alteração de teste kits nos dados e também no banco de dados em produção.

**Comment by jaumpedro214** [comment]
Correção feita no código. Pendente a correção no banco de produção.

**Comment by jaumpedro214** [comment]
Correção feita no banco de produção.



![Image](https://github.com/user-attachments/assets/c44de9cb-3ebe-40eb-9b46-42804f25b035)
