### ISSUE TITLE
Pipeline para dados do InfoDengue

### ISSUE THREAD

**Issue by andersonbrito** [InstitutoTodosPelaSaude/arbo#168]
Precisamos incorporar a extração automática dos dados de nowcasting do Infodengue como parte dos outputs dos ETLs semanais de arbo.

@BragatteMAS já desenvolveu scripts que extraem esses dessa API: https://info.dengue.mat.br/services/api/doc

Temos interesse em ter numa tabela os dados de casos de dengue, chikungunya e Zika, por município, corrigidos por nowcasting e sem a correção. Peço que verifiquem com o Bragatte quais campos de dados nos interessam.

A idéia seria gerar uma grande tabela com contagens de casos, contendo: data, semana epidemiológica, número de casos (nowcasting), número de casos (brutos), cidade, estado, região. Nessa mesma tabela poderíamos ter os dados para os três vírus.

De posse desses dados poderemos gerar gráficos como este:
<img width="869" alt="Screenshot 2024-10-17 at 11 13 27" src="https://github.com/user-attachments/assets/0aa57425-60f3-4917-b3d5-59b20c7f5a0f">

Temos certa urgência: se possível, gostaríamos de ter esses dados disponíveis até o fim de novembro em nossos relatórios de arbovírus.

**Comment by mathdesilva** [comment]
@andersonbrito @BragatteMAS Existe alguma doença nessa API que vai para Respat? ou pegaremos apenas para Arbo?

**Comment by BragatteMAS** [comment]
Olá pessoas
@mathdesilva 
<img width="1723" alt="Captura de Tela 2024-10-22 às 19 09 52" src="https://github.com/user-attachments/assets/af55c2e6-a980-4cbe-9a8a-ef781ef1de48">
Coloquei os scripts no slack.

@andersonbrito essa API é focada somente em dados de arbovirus, especialmente dengue.
https://info.dengue.mat.br/
https://info.dengue.mat.br/services/api
